### ISSUE TITLE
Connection issues when running action on custom container

### ISSUE THREAD

**Issue by bertmelis** [Namoshek/mosquitto-github-action#4]
Hi,

I don't know if this is a configuration issue or something that needs to be fixed in the action itself.

I switched from installing all dependencies in the github action to running the action in a custom container with all dependencies preinstalled. Now, my mqtt client can not connect to the broker in your container anymore.
I tried connecting to localhost and by setting the hostname.

Is this a limitation in github actions?
Is something wrong with my configuration?

See https://github.com/bertmelis/espMqttClient/actions/runs/9938521654/job/27451130098

**Comment by Namoshek** [comment]
To be honest, I don't know what happens when you run this action in a container and how they interact. But as you already seem to have found out, you probably should use a service container for your use case as GitHub Actions will setup the Docker network correctly in such case.

**Comment by bertmelis** [comment]
Yes, a service container is the solution. Not a straightforward one though...
